# Name of the entire workflow, reflecting its purpose: building and linting a Go project
name: Go Build and Lint

# Triggers for the workflow: on push and pull request to the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Definition of jobs
jobs:
  # Job for building the project
  build:
    runs-on: ubuntu-latest # Runs on the latest Ubuntu version
    steps:
      # Step 1: Clone the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24' # Use Go version 1.24 as specified

      # Step 3: Build the project
      - name: Build
        run: go build -v ./... # Build all packages with verbose output

  # Job for running the linter
  lint:
    runs-on: ubuntu-latest # Also runs on Ubuntu
    steps:
      # Step 1: Clone the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Go (required for golangci-lint)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24' # Same Go version as in the build job

      # Step 3: Run golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1 # Use the specified version v6.0.1
